#on:
#  push:
#    branches:
#      - staging
#name: 🚀 Deploying to staging
#jobs:
#  web-deploy:
#    name: 🎉 Deploy
#    runs-on: ubuntu-latest
#    steps:
#    - name: 🚚 Get latest code
#      uses: actions/checkout@v2.1.0
#
#    - name: 📂 Sync files
#      uses: SamKirkland/FTP-Deploy-Action@4.1.0
#      with:
#        server: ftp.shelta.tech
#        username: ${{ secrets.FTP_USERNAME }}
#        password: ${{ secrets.FTP_PASSWORD }}
#        server-dir: /staging.shelta.tech/








#name: Deploy

# Trigger the workflow on push and
# pull request events on the production branch
#on:
#  push:
#    branches:
#      - staging
#  pull_request:
#    branches:
#      - staging
#
#
## Authenticate to the the server via sshh
## and run our deployment script
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Deploy to server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          port: ${{ secrets.PORT }}
#          key: ${{ secrets.SSHKEY }}
#          script: "cd /var/www/html && ./.scripts/deploy.sh"
#          server-dir: /staging.shelta.tech/
#






name: Pushing to the staging server

on:
  push:
    branches:
      - staging
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Remove vendor directory
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd www/site_dir/
            [ -d ./vendor ] && rm -rf ./vendor
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Create zipped vendor directory
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./vendor.zip ./vendor

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp.shelta.tech
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}

  post-deploy:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Run migrations and seeders, clear cache for views, config and routes
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd www/site_dir/
            unzip -qq ./vendor.zip
            rm -f vendor.zip
            php artisan migrate:fresh --seed
            php artisan config:clear
            php artisan view:clear
            php artisan route:cache
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
